// examples/angular-app/src/app/app.component.ts
import { Component, OnDestroy, computed, effect } from '@angular/core';
  import { createSyncrSignal } from '@syncr/angular';
import { apiChannel, enableSyncrConsoleDevtools, tapChannel, storageEncryptedChannel, broadcastChannel } from '@syncr/core';

  type Filters = { q: string; sort: 'date'|'name'; page: number };
  const defaults: Filters = { q:'', sort:'date', page:1 };

  @Component({
    selector: 'app-root',
    standalone: true,
    template: \`
      <main style="font-family: system-ui; padding: 24px;">
        <h1>Syncr Angular Demo</h1>
        <p>Search, change sort, change page, refresh the browser — state persists via URL + localStorage.</p>

        <label>
          Search:
          <input [value]="filters().q" (input)="onQ($event)" />
        </label>

        <label style="margin-left: 12px;">
          Sort:
          <select [value]="filters().sort" (change)="onSort($event)">
            <option value="date">Date</option>
            <option value="name">Name</option>
          </select>
        </label>

        <div style="margin-top: 12px;">
          <button (click)="prevPage()" [disabled]="filters().page === 1">Prev</button>
          <span style="margin: 0 8px;">Page {{ filters().page }}</span>
          <button (click)="nextPage()">Next</button>
        </div>

        <pre style="background:#111; color:#0f0; padding:12px; border-radius:6px; margin-top:16px;">
{{ filters() | json }}
        </pre>
      </main>
    \`
  })
  export class AppComponent implements OnDestroy {
  constructor(){ enableSyncrConsoleDevtools(); }
    syn = createSyncrSignal<Filters>({
      key: 'ngFilters',
      defaultValue: defaults,
      channels: [
        'url',
        storageEncryptedChannel<Filters>('ngFilters', { passphrase: 'demo-pass' }),
        tapChannel(apiChannel<Filters>('ngFilters', { baseUrl: 'http://localhost:4321' })),
        broadcastChannel<Filters>('ngFilters')
      ],
      debounceMs: 200
    });

    filters = this.syn.state;

    onQ(ev: Event){
      const q = (ev.target as HTMLInputElement).value;
      this.syn.set(prev => ({ ...prev, q, page: 1 }));
    }
    onSort(ev: Event){
      const sort = (ev.target as HTMLSelectElement).value as Filters['sort'];
      this.syn.set(prev => ({ ...prev, sort }));
    }
    nextPage(){ this.syn.set(prev => ({ ...prev, page: prev.page + 1 })); }
    prevPage(){ this.syn.set(prev => ({ ...prev, page: Math.max(1, prev.page - 1) })); }

    ngOnDestroy(){ this.syn.destroy(); }
  }

// examples/react-app/src/App.tsx
import React from 'react';
import { useSyncr } from '@syncr/react';
import { apiChannel, enableSyncrConsoleDevtools, tapChannel, storageEncryptedChannel, broadcastChannel } from '@syncr/core';

type Filters = { q:string; sort:'date'|'name'; page:number };
const defaults: Filters = { q:'', sort:'date', page:1 };

export default function App(){
const [useServer, setUseServer] = React.useState(false);
const [devtools, setDevtools] = React.useState(false);
  const [encrypted, setEncrypted] = React.useState(false);
  const [broadcast, setBroadcast] = React.useState(false);

const channels = React.useMemo(() => {
  const list: any[] = ['url'];
        if (encrypted) { list.push(storageEncryptedChannel<Filters>('filters', { passphrase: 'demo-pass' })); } else { list.push('storage'); }
  if (useServer) list.push(apiChannel<Filters>('filters', { baseUrl: 'http://localhost:4321' }));
        if (broadcast) list.push(broadcastChannel<Filters>('filters'));
  return devtools ? list.map(ch => typeof ch === 'string' ? ch : tapChannel(ch)) : list;
  }, [useServer, devtools]);

  const [filters, setFilters] = useSyncr<Filters>({
    key: 'filters',
    defaultValue: defaults,
    channels,
    debounceMs: 200
  });

  const onQ = (e: React.ChangeEvent<HTMLInputElement>) => {
    const q = e.target.value;
    setFilters(prev => ({ ...prev, q, page: 1 }));
  };

  const onSort = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const sort = e.target.value as Filters['sort'];
    setFilters(prev => ({ ...prev, sort }));
  };

  const nextPage = () => setFilters(prev => ({ ...prev, page: prev.page + 1 }));
  const prevPage = () => setFilters(prev => ({ ...prev, page: Math.max(1, prev.page - 1) }));

  return (
    <div style={{ fontFamily: 'system-ui', padding: 24 }}>
<label style={{display:'block'}}><input type='checkbox' checked={useServer} onChange={e=>setUseServer(e.target.checked)} /> Sync with Server</label>
<label style={{display:'block'}}><input type='checkbox' checked={devtools} onChange={e=>{setDevtools(e.target.checked); if(e.target.checked) enableSyncrConsoleDevtools();}} /> Enable DevTools logging</label>
<label style={{display:'block'}}><input type='checkbox' checked={encrypted} onChange={e=>setEncrypted(e.target.checked)} /> Encrypted storage</label>
<label style={{display:'block'}}><input type='checkbox' checked={broadcast} onChange={e=>setBroadcast(e.target.checked)} /> Cross-tab Broadcast</label>
      <h1>Syncr React Demo</h1>
      <p>Try typing in the search box, changing sort, and paging. Refresh the page or copy the URL to see state persistence via URL + localStorage.</p>

      <label>
        Search: <input value={filters.q} onChange={onQ} placeholder="Type to search..." />
      </label>
      <label style={{ marginLeft: 12 }}>
        Sort:
        <select value={filters.sort} onChange={onSort}>
          <option value="date">Date</option>
          <option value="name">Name</option>
        </select>
      </label>

      <div style={{ marginTop: 12 }}>
        <button onClick={prevPage} disabled={filters.page===1}>Prev</button>
        <span style={{ margin: '0 8px' }}>Page {filters.page}</span>
        <button onClick={nextPage}>Next</button>
      </div>

      <pre style={{ background:'#111', color:'#0f0', padding:12, borderRadius:6, marginTop:16 }}>
        {JSON.stringify(filters, null, 2)}
      </pre>
    </div>
  );
}
